version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: enes6113905
      POSTGRES_DB: tasksdb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
